In [3]:
import json
import torch
from gensim.models import KeyedVectors
from gensim import matutils
import numpy as np

In [4]:
print('Loading Vocabulary and Vectors')
word2vec = KeyedVectors.load_word2vec_format(
    'data/word2vec/GoogleNews-vectors-negative300.bin', binary=True)
vocabulary = json.load(open('data/processed_data/processed_data.json', 'r'))

Loading Vocabulary and Vectors


In [5]:
target = torch.tensor([[1051,   26,  337,  110,  960,    5,  190,  708,   28,  196,  435,  296,
          247, 6134, 3361,   99,   25,  247,  837,  721,    5, 1012,   12, 1927,
         3721,   51,   55,   56,   57,    1,   58,    1,   59,    1,   33,   60,
           52,  247, 1435, 6134]])

generated = torch.tensor([[6135, 4049,  326, 5387, 4024, 5655, 2617, 2519, 3334, 2143, 4185, 1754,
         4004, 3380, 3529, 1859, 5953, 2486, 2173,  696, 1380, 1146, 1549, 3550,
         4678, 5196, 3248, 1274, 5321, 5632, 5090,  303, 2230, 1095, 1516, 1701,
          832, 1320, 4130, 2822,   44]])

In [6]:
def word2vec_emb(sequence, word2vec, vocabulary):
    
    seq_tokens = []
    for key in sequence:
        seq_tokens.append(vocabulary['ind2word'][str(key.item())])
    
    vectorized = []
    for word in seq_tokens:
        try:
            vectorized.append(word2vec[word])
        except:
            vectorized.append(word2vec['UNK'])
    
    return np.array(vectorized)

In [7]:
def similarity_cosine(vec1, vec2):
    cosine_similarity = np.dot(matutils.unitvec(vec1), matutils.unitvec(vec2))
    return cosine_similarity

In [8]:

def reward(target, generated, word2vec, vocabulary):
    '''
    Calculate the reward for the generated text
    '''
    target = word2vec_emb(target, word2vec, vocabulary)
    generated = word2vec_emb(generated, word2vec, vocabulary)
    
    print(target)
    print('------------------')
    print(generated)
    reward = similarity_cosine(target.mean(axis=0), generated.mean(axis=0))

    return reward

In [9]:
reward(target=target[0], generated=generated[0][1:],
          word2vec=word2vec, vocabulary=vocabulary)

[[-0.18066406  0.00726318  0.01989746 ... -0.09570312  0.00466919
  -0.20800781]
 [-0.01574707 -0.02832031  0.08349609 ...  0.00686646  0.06103516
  -0.1484375 ]
 [ 0.05981445  0.02380371  0.06738281 ... -0.10986328 -0.00872803
   0.03710938]
 ...
 [-0.09472656 -0.51171875  0.05810547 ...  0.390625   -0.00338745
   0.28125   ]
 [-0.09472656 -0.51171875  0.05810547 ...  0.390625   -0.00338745
   0.28125   ]
 [-0.09472656 -0.51171875  0.05810547 ...  0.390625   -0.00338745
   0.28125   ]]
[[ 0.37109375  0.0246582  -0.33203125 ... -0.11767578  0.19335938
   0.578125  ]
 [ 0.00921631  0.09960938 -0.03979492 ...  0.13671875  0.07666016
   0.13867188]
 [-0.10546875 -0.13574219 -0.12402344 ... -0.0088501   0.09863281
  -0.29492188]
 ...
 [ 0.38085938  0.04174805  0.00180817 ...  0.06225586 -0.23046875
  -0.06787109]
 [-0.22265625 -0.14160156  0.20214844 ... -0.15917969  0.11962891
   0.16992188]
 [ 0.05371094  0.4453125   0.17675781 ...  0.08251953  0.28125
  -0.16601562]]


0.5414183

In [12]:
torch.tensor([[10]]).detach()

tensor([[10]])

In [38]:
mse_criterion = torch.nn.MSELoss()

In [14]:
word2vec_emb(generated[0][1:], word2vec, vocabulary)

array([[ 0.37109375,  0.0246582 , -0.33203125, ..., -0.11767578,
         0.19335938,  0.578125  ],
       [ 0.00921631,  0.09960938, -0.03979492, ...,  0.13671875,
         0.07666016,  0.13867188],
       [-0.10546875, -0.13574219, -0.12402344, ..., -0.0088501 ,
         0.09863281, -0.29492188],
       ...,
       [ 0.38085938,  0.04174805,  0.00180817, ...,  0.06225586,
        -0.23046875, -0.06787109],
       [-0.22265625, -0.14160156,  0.20214844, ..., -0.15917969,
         0.11962891,  0.16992188],
       [ 0.05371094,  0.4453125 ,  0.17675781, ...,  0.08251953,
         0.28125   , -0.16601562]], dtype=float32)

In [17]:
mse_criterion(torch.tensor([1,2,34,4.4,4]),1)

AttributeError: 'int' object has no attribute 'size'

In [33]:
a = word2vec_emb(generated[0][1:], word2vec, vocabulary)
a = torch.tensor(a)

In [36]:
a.size()
input = torch.rand(40, 300)
input

tensor([[0.9195, 0.4132, 0.1352,  ..., 0.2907, 0.8835, 0.4515],
        [0.9105, 0.2878, 0.2476,  ..., 0.2693, 0.7531, 0.7952],
        [0.0973, 0.4504, 0.8991,  ..., 0.2313, 0.4361, 0.1376],
        ...,
        [0.4261, 0.0687, 0.6613,  ..., 0.6741, 0.0232, 0.9044],
        [0.9803, 0.1017, 0.4276,  ..., 0.8148, 0.9970, 0.1829],
        [0.1486, 0.8471, 0.9209,  ..., 0.7939, 0.7246, 0.3602]])

In [46]:
o = mse_criterion(    torch.tensor(a) ,input)

C:\Users\anest\AppData\Local\Temp\ipykernel_22720\42727384.py:1: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  o = mse_criterion(    torch.tensor(a) ,input)


In [43]:
o = torch.mean(mse_criterion(    torch.tensor(a) ,input), 0)

C:\Users\anest\AppData\Local\Temp\ipykernel_22720\3427681131.py:1: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  o = torch.mean(mse_criterion(    torch.tensor(a) ,input), 0)


In [48]:
o.backward()

RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn

In [50]:
loss = torch.nn.MSELoss()
input = torch.randn(3, 5, requires_grad=True)
target = torch.randn(3, 5)
output = loss(input, target)
output.backward()

In [51]:
scores = rouge.get_scores(
    generated_summary, reference_summary
)
print(scores)

tensor(1.6194, grad_fn=<MseLossBackward0>)